/*
 *   This file was generated by a tool.
 *   Do not edit it, otherwise the changes will be overwritten.
 */

using System;
using UnityEngine;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using WJExcelDataClass;

[Serializable]
public class DataManager //: SingletonTemplate<DataManager>
{
	public Model p_Model;

	public ModelItem GetModelItemByID(Int32 id)
	{
		ModelItem t = null;
		p_Model.Dict.TryGetValue(id, out t);
		if (t == null) Debug.LogError("can't find the id " + id + " in Model");
		return t;
	}

	public void LoadAll()
	{
		p_Model = Load("Model") as Model;
	}

	private System.Object Load(string name)
	{
		IFormatter f = new BinaryFormatter();
		TextAsset text = Resources.Load<TextAsset>("BinConfigData/" + name);
		Stream s = new MemoryStream(text.bytes);
		System.Object obj = f.Deserialize(s);
		s.Close();
		return obj;
	}
}

